//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DiskScan.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DISKSCAN_FORM               101
#define IDD_FAT32INFOVIEW               103
#define IDR_MAINFRAME                   128
#define IDR_DISKSCTYPE                  129
#define IDD_DVE_LIST                    130
#define IDR_FAT32TYPE                   130
#define IDR_VOLTYPE                     131
#define IDC_DE_LIST                     131
#define IDD_INFO                        131
#define IDD_DEV_INFO                    132
#define IDS_NTFSTYPE                    132
#define IDD_DVE_VOLUME                  133
#define IDS_DEV_NAME                    133
#define IDI_FILE                        134
#define IDD_INFOVIEW                    134
#define IDS_CAN_PART                    134
#define IDI_FOLDER                      135
#define IDD_DIALOG2                     136
#define IDC_DATA_CTRL                   137
#define IDC_ET_OFFSET                   138
#define IDC_ET_DATA                     139
#define IDC_ET_CHAR                     140
#define IDC_VSCROLL                     141
#define IDC_ET_DEV_NAME                 142
#define IDR_NTFSTYPE                    142
#define IDC_ST_CAN_PART_SIZE            143
#define IDC_ET_CAN_PART_BYTE            144
#define IDC_ET_CAN_PART_SIZE            145
#define IDC_ST_BYTE_PER_SECTOR          146
#define IDC_ET_BYTE_PER_SECTOR          147
#define IDC_ST_SECTOR_PER_TRACK         148
#define IDC_ET_SECTOR_PER_TRACK         149
#define IDD_FAT32_FILE                  149
#define IDC_ST_CAN_PART_AREA            150
#define IDR_FAT32_FILE_MENU             150
#define IDR_NTFS_FILE_MENU              151
#define IDC_ST_DEV_NAME                 151
#define IDD_PROGRESS                    151
#define IDR_FAT32_FILE_MENU0            152
#define IDC_ST_TRACK_PER_CYLINDER       152
#define IDD_NTFS_FILE                   152
#define IDC_ET_TRACK_PER_CYLINDER       153
#define IDR_NTFS_FILE_ATTR_LIST_MENU    153
#define IDC_ST_CYLINDERS                154
#define IDC_ET_CYLINDERS                155
#define IDC_ST_CAN_NOT_PART_AREA        156
#define IDI_DVD_ROM                     156
#define IDC_ST_CAN_NOT_PART_SIZE        157
#define IDC_ET_CAN_NOT_PART_BYTE        158
#define IDI_UNKNOW_VOL                  158
#define IDC_ET_CAN_NOT_PART_SIZE        159
#define IDI_REMOTE_VOL                  159
#define IDC_ST_NO_PART_SIZE             160
#define IDI_FLOPY_VOL                   160
#define IDC_ET_NO_PART_BYTE             161
#define IDI_ICON1                       161
#define IDI_REMOVABLE_VOL               161
#define IDC_ET_NO_PART_SIZE             162
#define IDC_ST_LOGICAL_DRIVER_AREA      163
#define IDC_ST_LOGICAL_DRIVER_COUNT     164
#define IDC_ET_LOGICAL_DRIVER_COUNT     165
#define IDC_ST_MAIN_PART_COUNT          166
#define IDC_ET_MAIN_PART_COUNT          167
#define IDC_ST_LOGICAL_PART_COUNT       168
#define IDC_ET_LOGICAL_PART_COUNT       169
#define IDC_ST_DEV_INFO_AREA            170
#define IDC_ST_DEV_AREA_INDEX           171
#define IDC_ET_DEV_AREA_INDEX           172
#define IDC_ST_START_SECTOR             173
#define IDC_ET_START_SECTOR             174
#define IDC_ST_PART_INFO_AREA           175
#define IDC_ST_PART_NAME                176
#define IDC_ET_PART_NAME                177
#define IDC_ST_PART_SIZE                178
#define IDC_ET_PART_SIZE_BYTE           179
#define IDC_ET_PART_SIZE                180
#define IDC_ST_SECTOR_COUNT             181
#define IDC_ET_SECTOR_COUNT             182
#define IDC_ST_RESERVE_SECTOR           183
#define IDC_ET_RESERVE_SECTOR           184
#define IDC_ST_SECTOR_PER_CLUST         185
#define IDC_ET_SECTOR_PER_CLUST         186
#define IDC_ST_SECTOR_PER_FAT           187
#define IDC_ET_SECTOR_PER_FAT           188
#define IDC_ST_FAT1                     189
#define IDC_ET_FAT1                     190
#define IDC_ST_FAT2                     191
#define IDC_ET_FAT2                     192
#define IDC_ST_FSINFO                   193
#define IDC_ET_FSINFO                   194
#define IDC_ST_ROOT_DIR                 195
#define IDC_ET_ROOT_DIR                 196
#define IDC_ST_REMAIN_SECTOR_ARER       197
#define IDC_ST_REMAIN_SECTOR_POS        198
#define IDC_ET_REMAIN_SECTOR_POS        199
#define IDC_ST_REMAIN_SECTOR_COUNT      200
#define IDC_ET_REMAIN_SECTOR_COUNT      201
#define IDC_ST_REMAIN_SECTOR_SIZE       202
#define IDC_ET_REMAIN_SECTOR_SIZE       203
#define IDC_ST_MFT_CLUST                204
#define IDC_ET_MFT_CLUST                205
#define IDC_ST_MFTMIRR_CLUST            206
#define IDC_ET_MFTMIRR_CLUST            207
#define IDC_ST_FILE_SYSTEM              208
#define IDC_ET_FILE_SYSTEM              209
#define IDC_ST_DATA_SCAN_AREA           210
#define IDC_ST_SECTOR_SCAN              211
#define IDC_ET_SECTOR_NUM               212
#define IDC_BTN_PRE_SECTOR              213
#define IDC_BTN_NEXT_SECTOR             214
#define IDC_BTN_FIRST_SECTOR            215
#define IDC_BTN_LAST_SECTOR             216
#define IDC_ST_CLUST_SCAN               217
#define IDC_ET_CLUST_NUM                218
#define IDC_BTN_PRE_CLUST               219
#define IDC_BTN_NEXT_CLUST              220
#define IDC_BTN_FIRST_CLUST             221
#define IDC_BTN_LAST_CLUST              222
#define IDC_DEV_AND_VOLUME              1000
#define IDC_FILE_PATH                   1002
#define IDC_CK_READ_ONLY                1003
#define IDC_CK_SYSTEM                   1004
#define IDC_CK_DIR                      1005
#define IDC_CK_ARTRIVE                  1006
#define IDC_CK_DEVICE                   1006
#define IDC_CK_HIDDEN                   1007
#define IDC_CK_VOL_ID                   1008
#define IDC_CK_TEMP                     1008
#define IDC_CK_REPARSE_POINT            1009
#define IDC_CK_SPARSE                   1010
#define IDC_CK_COMPRESSED               1011
#define IDC_FAT2_LIST                   1012
#define IDC_CK_ENCRYPTED                1012
#define IDC_OK                          1013
#define IDC_FAT1_LIST                   1015
#define IDC_COPY_PROGRESS               1017
#define IDC_CK_NORMAL                   1017
#define IDC_ST_PROGRESS                 1018
#define IDC_CUSTOM1                     1021
#define IDC_LIST1                       1022
#define IDC_NTFS_FILE_ATTR_LIST         1022
#define IDC_CK_ARCHIVE                  1024
#define IDC_PARENT_MFT                  1025
#define IDC_MFT_NUM                     1026
#define ID_INDICATOR_CUR_VIEW           1027
#define IDC_CONTENT_LIST                32771
#define ID_FILE_OPEN_1                  32772
#define IDC_DISK_CONTENT_LIST           32789
#define IDC_FAT3_DIR_LIST               32790
#define IDC_NTFS_DIR_LIST               32791
#define ID_POS_PARAENT_DIR              32795
#define ID_SERVE_AS                     32796
#define ID_FILE_ATTR                    32797
#define ID_POS_DATA                     32800
#define ID_FAT32_POS_DATA               32803
#define ID_FAT32_POS_PARAENT_DIR        32804
#define ID_FAT32_SERVE_AS               32805
#define ID_FAT32_FILE_ATTR              32806
#define ID_NTFS_POS_MFT                 32807
#define ID_NTFS_POS_PARAENT_DIR         32808
#define ID_NTFS_SERVE_AS                32809
#define ID_NTFS_FILE_ATTR               32810
#define ID_32811                        32811
#define ID__32812                       32812
#define ID__32813                       32813
#define ID__32814                       32814
#define ID_POS_STD_ATTR_HEAD            32815
#define ID_POS_STD_ATTR_DATA            32816
#define ID_SEVER_ATTR                   32817
#define ID_32818                        32818
#define ID_OPEN_FILE                    32819
#define IDC_OPEN_FILE_DIR               32820
#define ID__32821                       32821
#define ID_CHECK_DELETE_FILE            32822
#define ID__32823                       32823
#define IDS_PHYSC_DISK                  61216
#define IDS_LOGICAL_DRIVER              61217
#define IDS_NOT_VALIDE_NAME             61218
#define IDS_PROMPT                      61219
#define IDS_OPEN_FALIED                 61220
#define IDS_ERROR                       61221
#define IDS_ID                          61222
#define IDS_FILE_NAME                   61223
#define IDS_TYPE                        61224
#define IDS_START_SECTOR                61225
#define IDS_SECTOR_COUNT                61226
#define IDS_SIZE                        61227
#define IDS_NO_USE_PART                 61228
#define IDS_FAT32_PART                  61229
#define IDS_XENIX_ROOT_PART             61230
#define IDS_XENIX_USR_PART              61231
#define IDS_FAT16_PART                  61232
#define IDS_EXT_PART                    61233
#define IDS_NTFS_PART                   61234
#define IDS_AIX_PART                    61235
#define IDS_AIX_BOOTABLE_PART           61236
#define IDS_SO2_BOOT_MG_PART            61237
#define IDS_OPUS_PART                   61238
#define IDS_HID_FAT12_PART              61239
#define IDS_COMPAQ_DIAG_PART            61240
#define IDS_AST_WINDOWS_SWAP_PART       61241
#define IDS_HID_VFAT_PART               61242
#define IDS_NEC_DOS_PART                61243
#define IDS_PART_MAGIC_PART             61244
#define IDS_VENIX_80286_PART            61245
#define IDS_PPC_PREP_PART               61246
#define IDS_SFS_PART                    61247
#define IDS_QNX4_PART                   61248
#define IDS_ONTRACK_DM_PART             61249
#define IDS_CP_M_PART                   61250
#define IDS_EZ_DRIVE_PART               61251
#define IDS_GOLDEN_BOW_PART             61252
#define IDS_PRIAM_EDICK_PART            61253
#define IDS_SPEED_STOR_PART             61254
#define IDS_GNU_HURD_PART               61255
#define IDS_NOVELL_NOTWARE_PART         61256
#define IDS_DISK_SECURE_MULT_PART       61257
#define IDS_PC_IX_PART                  61258
#define IDS_OLD_MINIX_PART              61259
#define IDS_MINIX_OLD_LINUX_PART        61260
#define IDS_LINUX_SWAP_PART             61261
#define IDS_LINUX_PART                  61262
#define IDS_OS2_HID_C_PART              61263
#define IDS_LINUX_EXT_PART              61264
#define IDS_NTFS_VOLUM_SET_PART         61265
#define IDS_AMOEBA_PART                 61266
#define IDS_AMOEBA_BBT_PART             61267
#define IDS_THINKPAD_HID_PART           61268
#define IDS_BSD_386_PART                61269
#define IDS_OPEN_BSD_PART               61270
#define IDS_NEXT_STEP_PART              61271
#define IDS_BSDI_FS_PART                61272
#define IDS_BSDI_SWAP_PART              61273
#define IDS_SOLAIS_BOOT_PART            61274
#define IDS_DR_OS_NOVELL_PART           61275
#define IDS_SYRINX_PART                 61276
#define IDS_CP_M_CTOS_PART              61277
#define IDS_DOS_ACCESS_PART             61278
#define IDS_DOS_R0_PART                 61279
#define IDS_BEOS_FS_PART                61281
#define IDS_DOS_3_3_PART                61282
#define IDS_LAN_STEP_PART               61283
#define IDS_BBT_PART                    61284
#define IDS_MBR_PART                    61285
#define IDS_EBR_PART                    61286
#define IDS_EMPTY_PART                  61287
#define IDS_REMAIN_PART                 61288
#define IDS_UNKNOW_PART                 61289
#define IDS_CREATE_TIME                 61290
#define IDS_MODIFY_TIME                 61291
#define IDS_ACCESS_TIME                 61292
#define IDS_ALLOC_SIZE                  61293
#define IDS_REAL_SIZE                   61294
#define IDS_MFT_RECODE                  61295
#define IDS_MFT_MODIFY_TIME             61296
#define IDS_FILE_MODIFY_TIME            61297
#define IDS_MBR_NAME                    61298
#define IDS_EBR_NAME                    61299
#define IDS_EMPTY_PART_NAME             61300
#define IDS_REMAIN_PART_NAME            61301
#define IDS_MAIN_PART                   61302
#define IDS_ACTIVITY_PART               61303
#define IDS_YES                         61304
#define IDS_NO                          61305
#define IDS_BYTE_PER_SECTOR             61306
#define IDS_SECTOR_PER_TRACK            61307
#define IDS_DISK_INFO                   61308
#define IDS_CAN_PART_AREA               61308
#define IDS_TRACK_PER_CYLINDER          61309
#define IDS_CYLINDERS                   61310
#define IDS_CAN_NOT_PART_AREA           61311
#define IDS_CAN_NOT_PART                61312
#define IDS_NO_PART                     61313
#define IDS_LOGICAL_DRIVER_AREA         61314
#define IDS_LOGICAL_DRIVER_COUNT        61315
#define IDS_MAIN_PART_COUNT             61316
#define IDS_LOGICAL_PART_COUNT          61317
#define IDS_DEV_AREA_INDEX              61318
#define IDS_DEV_INFO_AREA               61319
#define IDS_PART_INFO                   61320
#define IDS_PART_NAME                   61321
#define IDS_PART_SIZE                   61322
#define IDS_RESERVE_SECTOR              61323
#define IDS_SECTOR_PER_CLUST            61324
#define IDS_FAT1                        61325
#define IDS_FAT2                        61326
#define IDS_FSINFO                      61327
#define IDS_ROOT_DIR                    61328
#define IDS_REMAIN_SECTOR_COUNT         61329
#define IDS_REMAIN_SECTOR_SIZE          61330
#define IDS_SECTOR_PER_FAT              61331
#define IDS_MFT                         61332
#define IDS_MFTMIRR                     61333
#define IDS_FILE_SYSTEM                 61334
#define IDS_DATA_SCAN_AREA              61335
#define IDS_SECTOR_SCAN                 61336
#define IDS_WARNING                     61337
#define IDS_INVALID_CHAR                61338
#define IDS_SECTOR_NUM_ERR              61339
#define IDS_CLUST_SCAN                  61340
#define IDS_CLUST_NUM_ERR               61341
#define IDS_GET_FILE_ATTR_ERR           61342
#define IDS_CLUST_NUM                   61343
#define IDS_COPY_FAILED                 61344
#define IDS_SCAN                        61345
#define IDS_ATTR_ID                     61346
#define IDS_ATTR_NAME                   61347
#define IDS_ATTR_TYPE                   61348
#define IDS_ATTR_RESIDENT               61349
#define IDS_ATTR_SIZE                   61350
#define IDS_ATTR_COMPRESSED             61351
#define IDS_ATTR_ENCRYPTED              61352
#define IDS_ATTR_SPARSE                 61353
#define IDS_AD_STANDARD_INFORMATION     61354
#define IDS_AD_ATTRIBUTE_LIST           61355
#define IDS_AD_FILE_NAME                61356
#define IDS_AD_VOLUME_VERSION           61357
#define IDS_AD_OBJECT_ID                61358
#define IDS_AD_SECURITY_DESCRIPTOR      61359
#define IDS_AD_VOLUME_NAME              61360
#define IDS_AD_VOLUME_INFORMATION       61361
#define IDS_AD_DATA                     61362
#define IDS_AD_INDEX_ROOT               61363
#define IDS_AD_INDEX_ALLOCATION         61364
#define IDS_AD_BITMAP                   61365
#define IDS_AD_SYMBOL_LINK              61366
#define IDS_AD_REPARSE_POINT            61367
#define IDS_AD_EA_INFORMATION           61368
#define IDS_AD_EA                       61369
#define IDS_AD_PROPERTY_SET             61370
#define IDS_AD_LOGGED_UNTILITY_STREAM   61371
#define IDS_YES_HOOK                    61372
#define IDS_READ_ATTR_FAILED            61373
#define IDS_READ_ATTR_SUCCESS           61374
#define IDS_SELECT_FILE_DIR             61375
#define IDS_INVALID_PATH                61376
#define IDS_GET_DEV_INTO_ERR            61377
#define IDS_LINUX_LVM                   61378
#define IDS_LOCAL_DISK                  61379
#define IDS_REMOVEABLE_DISK             61380
#define IDS_UNKOWE_DISK                 61381
#define IDS_VOL_REMOVEABLE              61382
#define IDS_VOL_LOCAL                   61383
#define IDS_VOL_REMOTE                  61384
#define IDS_VOL_CD_DVD                  61385
#define IDS_VOL_RAM_DISK                61386
#define IDS_VOL_UNKNOW                  61387

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
